# -*- mode: ruby -*-
# vi: set ft=ruby :

# ---------------------------------------
# Things that might need tweaking for your network
DOMAIN = 'billhazard.local'
HOSTNAME = "windsc"
SUBNET = '192.168.2'
SERVER_IP = "#{SUBNET}.10"
SERVER_MEMORY = 2048
# ---------------------------------------

# vagrant rdp is broken in vagrant 1.6.3 but you can use a native RDP client
Vagrant.require_version ">= 1.6.4"
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.cache.auto_detect = true if Vagrant.has_plugin?('vagrant-cachier')

# the virtualbox box with windows installed
  config.vm.box = "win2012serv"
  #config.vm.box_url = "file://win2012serv"

# communicate via winRDP instead of ssh:
  config.vm.communicator = 'winrm'

# Ensure that all networks are set to private
  config.windows.set_work_network = true

  config.vm.define "win", primary: true do |vmconfig|
    vmconfig.vm.network :private_network, ip: SERVER_IP
    vmconfig.vm.guest = :windows
    # setting of hostname does not work in the vagrant 1.6.3 windows guest
    vmconfig.vm.hostname = HOSTNAME
    vmconfig.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
    vmconfig.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    vmconfig.vm.network :forwarded_port, guest: 80, host: 8080, id: "http", auto_correct: true

    vmconfig.vm.provider :virtualbox do |vb|
      vb.gui = true
      vb.name = HOSTNAME
      vb.customize ["modifyvm", :id, "--memory", SERVER_MEMORY]
    end

  # DSC provisioner demo -- runs a PowerShell script to provision according to the
  # configuration in config.ps1

$script = <<SCRIPT
  Write-Host Hidy-ho from ($env:computername)!
  cd c:\\vagrant
  . c:\\vagrant\\config.ps1
  MyWebConfig
  Start-DscConfiguration -path c:\\vagrant\\MyWebConfig -wait -verbose
  Write-Host Done.
SCRIPT
    vmconfig.vm.provision 'shell', 
      inline: $script
    
  end

end
